#%%
# -*- coding: utf-8 -*-
"""FelipeCortesTarea1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tllZ0jRkaAW2-qOqjbqapQrnmr5L3gb3
"""

import numpy as np
n = np.arange(1, 101)
S = np.sum(np.exp(n) * (n + 1))
print(S)
# %%
# Nota: 7.0